### ISSUE TITLE
Multiple reference channels in a run

### ISSUE THREAD

**Issue by ekawaler** [Nesvilab/TMT-Integrator#11]
Hello! I'm curious as to how TMT-Integrator handles multiple reference channels in a single run. When I have, for instance, "pool15A" and "pool15B" in a single TMT run, both pools are missing from the header, but one of the pools still has a column in the actual data (so the header and the data have different numbers of columns). It does appear that they're both used in the calculations, though, as if I change one of the names so it's not counted as a reference, the data is different. Also, is there a way to easily drop columns? I'd love it if there was a prefix I could use, like the one used to mark reference columns, to say I'd rather not include a column in my analysis.

**Comment by huiyinc** [comment]
Hi,

Please specify your ref_tag to be a unique string. For example, the string,
*pool*, should only be in one channel if it is a reference tag. Otherwise,
TMT-Integrator will use the first column with the string as the reference.
Also, TMT-Integrator can't drop columns. Thanks.

Huiyin

ekawaler <notifications@github.com> 於 2020年11月5日 上午5:00 寫道：

﻿

Hello! I'm curious as to how TMT-Integrator handles multiple reference
channels in a single run. When I have, for instance, "pool15A" and
"pool15B" in a single TMT run, both pools are missing from the header, but
one of the pools still has a column in the actual data (so the header and
the data have different numbers of columns). It does appear that they're
both used in the calculations, though, as if I change one of the names so
it's not counted as a reference, the data is different. Also, is there a
way to easily drop columns? I'd love it if there was a prefix I could use,
like the one used to mark reference columns, to say I'd rather not include
a column in my analysis.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Nesvilab/TMT-Integrator/issues/11>, or unsubscribe
