### ISSUE TITLE
[Question] tmt-integrator output

### ISSUE THREAD

**Issue by skeffington** [Nesvilab/TMT-Integrator#12]
Hi, I just want to be absolutely certain I'm not misinterpreting the tmt-integrator output:

1) The abundance based outputs (eg Report_abundance_groupby=protein_protNorm=None_gu=0.tsv) - are these still on a log2(intensity) scale?

2) I can't quite get my head around the Ratio based output: Are they the ratio to the reference intensity (this doesn't seem to fit when I compare to the Abundance table)? And are they also still on a log2 scale?

3) What aggregation method is used to get protein intensities from the chosen  and normalised peptide intensities? Mean, geometric mean, median?

Sorry if I missed some of this in the docs - I just want to be sure!

Many thanks,
Alastair

**Comment by huiyinc** [comment]
Hi Alastair

1. Yes, both ratio- and abundance-based reports are in the log2 scale.
2. Yes, the ratios are the channel intensity to the reference intensity
(i.e., ratio=log2(the intensity of the ith channel/ the reference channel
intensity).
3. We use median for the aggregation.

Hope this helps. Thanks.

Huiyin

skeffington <notifications@github.com> 於 2020年12月4日 下午11:15 寫道：

﻿

Hi, I just want to be absolutely certain I'm not misinterpreting the
tmt-integrator output:

   1.

   The abundance based outputs (eg
   Report_abundance_groupby=protein_protNorm=None_gu=0.tsv) - are these still
   on a log2(intensity) scale?
   2.

   I can't quite get my head around the Ratio based output: Are they the
   ratio to the reference intensity (this doesn't seem to fit when I compare
   to the Abundance table)? And are they also still on a log2 scale?
   3.

   What aggregation method is used to get protein intensities from the
   chosen and normalised peptide intensities? Mean, geometric mean, median?

Sorry if I missed some of this in the docs - I just want to be sure!

Many thanks,
Alastair

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Nesvilab/TMT-Integrator/issues/12>, or unsubscribe
