### ISSUE TITLE
[question] Calculation of abundance in "abundance table"

### ISSUE THREAD

**Issue by jgriss** [Nesvilab/TMT-Integrator#13]
Hi,

Thanks a lot for the great tool!

I know that a similar question was already asked previously (see #12). Nevertheless, I'm not quite sure how you calculate the protein abundances.

According to the README normalisation vs. the reference channel is already performed at the PSM level.

Do you simply skip this step? If yes, is the reference channel still used for normalisation in the abundance table?

Thanks a lot for the help!

Kind regards,
Johannes

**Comment by huiyinc** [comment]
Hi Johannes,

Thanks for your request.
TMT-Integrator performs the normalization at both PSM and protein levels.
In the PSM-level normalization, the channel abundances are divided by the
reference abundance and the ratios are log2 transformed. After some steps
(e.g., outlier removal and abundance aggregation), the ratios are
normalized using median centering or global normalization (depending on
your parameter setting). In case you need more information, here are some
references:
- Clark, D. J. *et. al.*, Integrated Proteogenomic Characterization of
Clear Cell Renal Cell Carcinoma. Cell, 179(4): 964-983 e931.
- Djomehri, S. I. *et. al.*, Quantitative proteomic landscape of
metaplastic breast carcinoma pathological subtypes and their relationship
to triple-negative tumors. Nature Communications, 11(1): 1723.

We are also working on the manuscript which we believe will provide more
complete description of the workflow.
Thanks.

Huiyin

Johannes Griss <notifications@github.com> 於 2021年3月1日 下午7:07 寫道：

﻿

Hi,

Thanks a lot for the great tool!

I know that a similar question was already asked previously (see #12
<https://github.com/Nesvilab/TMT-Integrator/issues/12>). Nevertheless, I'm
not quite sure how you calculate the protein abundances.

According to the README normalisation vs. the reference channel is already
performed at the PSM level.

Do you simply skip this step? If yes, is the reference channel still used
for normalisation in the abundance table?

Thanks a lot for the help!

Kind regards,
Johannes

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Nesvilab/TMT-Integrator/issues/13>, or unsubscribe

**Comment by jgriss** [comment]
Hi @huiyinc ,

Thanks a lot for the quick response! The cell paper was very helpful and answered all my questions!

Kind regards,
Johannes
